version: '3'

volumes:
  pgdata:
  static_files:

services:
  python:
    build:
      context: .
      dockerfile: docker/prod/python/Dockerfile
    command: gunicorn -w 4 foodapp.wsgi -b 0.0.0.0:8000
    volumes:
      - .:/code
      - static_files:/static_files
    ports:
      - 8000:8000
  nginx:
    #image: nginx
    build:
      context: .
      dockerfile: docker/prod/nginx/Dockerfile
    volumes:
      - static_files:/static_files
    ports:
      - 8080:80